spring.application.name=orders-service

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/ordersdb
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:rootpass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=${KAFKA_HOST:localhost}:9092
app.kafka.topic.order-events=order-events

server.port=8080
